### PR TITLE
fix: config loader decode hook func bug

### LINKED ISSUE #2: Loader config bug when loading time duration
**Describe the bug**
This [commit](https://github.com/goto/salt/commit/471b7d35e587a29e6b298879c5df03527a806262) has a bug where it overrides the default decode hook functions.

**To Reproduce**
Load time duration config and it will throws error when loading it.

**Expected behavior**
Loading time duration config should be fine

We need to explicitly define all default decode hook functions.

### PR DESCRIPTION
**Pull request by mabdh**
close #2

### CODE REVIEW

File: config/config.go [hunk 1]
```diff
@@ -137,7 +137,11 @@ func NewLoader(options ...LoaderOption) *Loader {
 		v: getViperWithDefaults(),
 		opts: []viper.DecoderConfigOption{
 			viper.DecodeHook(
-				StringToJsonFunc(),
+				mapstructure.ComposeDecodeHookFunc(
+					StringToJsonFunc(),
+					mapstructure.StringToTimeDurationHookFunc(),
+					mapstructure.StringToSliceHookFunc(","),
+				),
```
Comment (bsushmith) [inline config/config.go:144]: Can we have test cases here so that this kind of bug can be found early? 🤔

Comment (mabdh) [reply config/config.go:144]: We can do that

**Review by bsushmith — APPROVED** [review]

**Review by haveiss — APPROVED** [review]
